
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-build
  labels:
    app : myapp3
    team: demo-team-b
    build-namespace: myapp3-build
    size: small
    environment: build
    goldilocks.fairwinds.com/enabled: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-dev
  labels:
    app : myapp3
    team: demo-team-b
    build-namespace: myapp3-build
    size: small
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-qa
  labels:
    app : myapp3
    team: demo-team-b
    build-namespace: myapp3-build
    size: small
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-prod
  labels:
    app : myapp3
    team: demo-team-b
    build-namespace: myapp3-build
    size: small
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
