
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-build
  labels:
    app : myapp1
    team: demo-team-b
    build-namespace: myapp1-build
    size: medium
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp1-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-dev
  labels:
    app : myapp1
    team: demo-team-b
    build-namespace: myapp1-build
    size: medium
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp1-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-qa
  labels:
    app : myapp1
    team: demo-team-b
    build-namespace: myapp1-build
    size: medium
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp1-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-prod
  labels:
    app : myapp1
    team: demo-team-b
    build-namespace: myapp1-build
    size: medium
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp1-build
