
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-build
  labels:
    app : myapp3
    team: group:default/demo-team-a
    build-namespace: myapp3-build
    size: medium
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp3-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-dev
  labels:
    app : myapp3
    team: group:default/demo-team-a
    build-namespace: myapp3-build
    size: medium
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp3-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-qa
  labels:
    app : myapp3
    team: group:default/demo-team-a
    build-namespace: myapp3-build
    size: medium
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp3-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp3-prod
  labels:
    app : myapp3
    team: group:default/demo-team-a
    build-namespace: myapp3-build
    size: medium
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp3-build
